### ISSUE TITLE
Amend nextCellGeneration to include probability

### ISSUE THREAD

**Issue by phoebe-wu** [philchapdelaine/cpsc312_p1#8]

**Comment by phoebe-wu** [comment]
did some research, thought about approaching it like this.. 
60% probability = generate a list of 60 1's and 40 0's and do random selection from that list.
If selection is 1, state changes. otherwise nothing.

idk how efficient it will be tho

**Comment by philchapdelaine** [comment]
Could we generate a random number from 1-100 and compare it to our probability number?

**Comment by phoebe-wu** [comment]
Having some difficulties 

- almost all random number generators return IO Integers which you cannot extract a regular Int from nor can you compare to a normal Int (was planning if chance p == 1 then execute)
- random number generators that do not use IO are apparently not truly random 

any other suggestions to how we could implement this?
